### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by bazzilic** [mayflaver/AsyncTorndb#2]
Hello,

What is the current status of the project? Is it being developed or it is abandoned? Is it safe to use in production, was it tested?

Thanks.

**Comment by Preffer** [comment]
@bazzilic You could have a look at https://github.com/PyMySQL/Tornado-MySQL

**Comment by bazzilic** [comment]
@Preffer yep, seen it, thanks! That is not the same though. I have a project that is using tornado since the DB module was still in there. I then switched to torndb as it required no changes to the code. I was now thinking of switching to AsyncTorndb, so that I can just add `yield` to the db requests. Switching to Tornado-MySQL would require much more changes to the code.
