### ISSUE TITLE
Official fork of PyMySQL supporting Tornado

### ISSUE THREAD

**Issue by YuzhongHuangCS** [mayflaver/AsyncTorndb#4]
I just find that PyMySQL have an official fork that support Tornado.
https://github.com/PyMySQL/Tornado-MySQL

I suggest merge this repo back or abandon.

**Comment by mayflaver** [comment]
That's really good. I would look  it at the end of holiday. thanks.

**Comment by mayflaver** [comment]
I open a new project - sora that provide a new function to make  protocol extends more easy.  I add higher level parser and I want to add more thing to replace iostream that's in deep develping.

**Comment by mayflaver** [comment]
happy chinese new year, by the end of holiday, I would take care about it, thanks. And sora is a new project I develped that will provide a new function for codec besides iostream, it will make protocol extends more easy. 

Sent from Huawei Mobile

PillowSky <notifications@github.com>编写：
